function Jdxdcc = Jdxdcc(X1,X2,X3,fx_c,fy_c,cx_c,cy_c,kc1,kc2,kc3,pc1,pc2)
%JDXDCC
%    JDXDCC = JDXDCC(X1,X2,X3,FX_C,FY_C,CX_C,CY_C,KC1,KC2,KC3,PC1,PC2)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    11-Aug-2016 17:44:09

Jdxdcc = reshape([1.0,0.0,0.0,1.0],[2, 2]);
