function Jdxdfc = Jdxdfc(X1,X2,X3,fx_c,fy_c,cx_c,cy_c,kc1,kc2,kc3,pc1,pc2)
%JDXDFC
%    JDXDFC = JDXDFC(X1,X2,X3,FX_C,FY_C,CX_C,CY_C,KC1,KC2,KC3,PC1,PC2)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    11-Aug-2016 17:44:09

t2 = 1.0./X3.^2;
t3 = X1.^2;
t4 = X2.^2;
t5 = t2.*t4;
t7 = t2.*t3;
t6 = t5+t7;
t8 = t6.^2;
t9 = 1.0./X3;
t10 = kc2.*t8;
t11 = kc3.*t6.*t8;
t12 = kc1.*t6;
t13 = t10+t11+t12+1.0;
Jdxdfc = reshape([pc2.*(t5+t2.*t3.*3.0)+X1.*t9.*t13+X1.*X2.*pc1.*t2.*2.0,0.0,0.0,pc1.*(t7+t2.*t4.*3.0)+X2.*t9.*t13+X1.*X2.*pc2.*t2.*2.0],[2, 2]);
