function Jdxdkc = Jdxdkc(X1,X2,X3,fx_c,fy_c,cx_c,cy_c,kc1,kc2,kc3,pc1,pc2)
%JDXDKC
%    JDXDKC = JDXDKC(X1,X2,X3,FX_C,FY_C,CX_C,CY_C,KC1,KC2,KC3,PC1,PC2)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    11-Aug-2016 17:44:09

t2 = 1.0./X3.^2;
t3 = 1.0./X3;
t4 = X1.^2;
t5 = t2.*t4;
t6 = X2.^2;
t7 = t2.*t6;
t8 = t5+t7;
t9 = t8.^2;
Jdxdkc = reshape([X1.*fx_c.*t3.*t8,X2.*fy_c.*t3.*t8,X1.*fx_c.*t3.*t9,X2.*fy_c.*t3.*t9,X1.*fx_c.*t3.*t8.*t9,X2.*fy_c.*t3.*t8.*t9,X1.*X2.*fx_c.*t2.*2.0,fy_c.*(t5+t2.*t6.*3.0),fx_c.*(t7+t2.*t4.*3.0),X1.*X2.*fy_c.*t2.*2.0],[2, 5]);
